AWSTemplateFormatVersion: '2010-09-09'
Description: Lambda Function
 
Resources:
  LambdaFunction:
    Type: AWS::Lambda::Function
    Properties: 
      Code:
        S3Bucket: lambda-repository-blake
        S3Key: lambda.zip
      Description: >
        EBS Backups
      Environment:
        Variables:
          REGION: us-west-2
      FunctionName: EBSBackups
      Handler: snapshots.lambda_handler
      Role: !GetAtt LambdaRole.Arn
      Runtime: python3.6
      Timeout: 31
 
  ScheduleRule:
    Type: "AWS::Events::Rule"
    Properties: 
      Description: Triggers EBS Backups Lambda
      ScheduleExpression: cron(30 04 * * ? *)
      State: ENABLED
      Targets:
        - Arn: !GetAtt LambdaFunction.Arn
          Id: "LambdaBackupsTrigger"

  LambdaRole:
    Type: AWS::IAM::Role
    Properties: 
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - lambda.amazonaws.com
            Action:
              - sts:AssumeRole         
      Path: /EBSBackups/
      Policies:
        - PolicyName: LambdaLog
          PolicyDocument: 
            Version: 2012-10-17
            Statement: 
              - Effect: Allow
                Action:
                  - logs:CreateLogGroup
                  - logs:CreateLogStream
                  - logs:PutLogEvents
                  - logs:DescribeLogStreams
                Resource: "arn:aws:logs:*:*:*"
        - PolicyName: EBSBackups
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Effect: Allow
                Action:
                  - ec2:DescribeInstances
                  - ec2:DeleteSnapshot
                  - ec2:ModifySnapshotAttribute
                  - ec2:CreateTags
                  - ec2:DescribeTags
                  - ec2:DescribeSnapshotAttribute
                  - ec2:DescribeInstanceAttribute
                  - ec2:DescribeVolumes
                  - ec2:CreateSnapshot
                  - ec2:DescribeSnapshots
                  - ec2:DescribeVolumeAttribute
                Resource: "*"

  PermissionForEventsToInvokeLambda: 
    Type: "AWS::Lambda::Permission"
    Properties: 
      FunctionName: !Ref "LambdaFunction"
      Action: "lambda:InvokeFunction"
      Principal: "events.amazonaws.com"
      SourceArn: !GetAtt ScheduleRule.Arn 
